use_modular_headers!



# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
prepare_react_native_project!

#linkage = ENV['USE_FRAMEWORKS']
#if linkage != nil
 # Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  #use_frameworks! :linkage => linkage.to_sym
#end

target 'barber' do
  config = use_native_modules!

  # RNWorklets removed (was added to support react-native-reanimated). Removed because
  # this project does not import reanimated; keeping it caused native build issues.

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Workaround: allow non-modular includes in framework modules to avoid
    # 'non-modular-include-in-framework-module' build errors for some RN pods.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end
end
